name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - run: npm install

      - name: Bump version
        id: bump_version
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          npm version patch --no-git-tag-version
          echo "VERSION=$(jq -r '.version' < package.json)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build --no-cache -t kadirkenan/hello-world-nodejs:${{ env.VERSION }} .

      - name: Push Docker image
        run: docker push kadirkenan/hello-world-nodejs:${{ env.VERSION }}

      - name: Commit version bump
        run: |
          git add package.json
          git commit -m "Bump version to ${{ env.VERSION }}"
          git push origin main --follow-tags
